# Generated by Django 3.2 on 2022-09-28 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mob', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='phone',
            field=models.CharField(max_length=12),
        ),
    ]
